### ISSUE TITLE
Create authentication as a node module

### ISSUE THREAD

**Issue by gaitonde** [appirio-tech/lc1-project#310] opened 2014-11-13 17:52 UTC
We have code that authenticates requests. This ticket is about creating that code as a node module that can be used by others, in particular, the Challenge and Discussion services.

**Comment by indytechcook** [comment] 2015-01-28 15:42
related to  #94 and #200

**Comment by indytechcook** [comment] 2015-01-28 15:56
closing as duplicate of #200

**Closed by indytechcook** 2015-01-28 15:56 UTC
Labels: Backlog
